### ISSUE TITLE
Support luajit 2.1 LJ_GC64 mode

### ISSUE THREAD

**Issue by lblasc** [corsix/ffi-reflect#5]
Hello,

Recently LuaJIT 2.1 branch enabled `LJ_GC64` mode by default. It would be great to have support for it, I find this library very useful.

Currently on x86_64 `reflect.getmetatable()` is giving me `Segmentation fault`.

**Comment by corsix** [comment]
I've pushed 4612bbd950461ff0ae09ecf71167c3d8addfcd2e - does that fix things for you?

**Comment by lblasc** [comment]
@corsix thank you, it works like a charm! Test suite is now only complaining on line 105 (#4).
